require 'spec_helper'

describe Authentication do
  subject { Authentication.new }

  it "should be valid when generated by FactoryGirl." do
    subject = Factory(:authentication)
    subject.should be_valid
  end

  it "should have an associated user." do
    subject.user = nil
    subject.should_not be_valid
  end

  it "should have an associated uid." do
    subject.uid = nil
    subject.should_not be_valid
  end
end
