embed_assets: on
s3_cache_control: 432000
s3_access_key_id: AKIAIRKVQDTWT2NN4J4Q
s3_secret_access_key: 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
s3_permission: public_read
s3_bucket: redu-assets
s3_upload_files:
  - public/images/new/**
  - public/javascripts/**
  - public/javascripts/ckeditor/**/**/**/*
  - public/stylesheets/**

javascripts:
  new_application:
    - public/javascripts/rails.js
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/lazyload.js
    - public/javascripts/asyncjs.jquery.js
    - public/javascripts/form.redu.jquery.js
    - public/javascripts/jquery.autosize.min.js
    - public/javascripts/vendor/placeholder-polyfill.min.js
    - public/javascripts/bootstrap-redu.js
    - public/javascripts/swfobject.js # Necessário ao browserdetection.js
    - public/javascripts/browserdetection.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/outdated-browser.js
    - public/javascripts/home.js
    - public/javascripts/statuses.js
    - public/javascripts/wall_spinner.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/timeago.js
    - public/javascripts/jquery.fcbkcomplete.min.js # Auto complete do facebook
    - public/javascripts/old-create-status.js
  landing:
    - public/javascripts/rails.js
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/lazyload.js
    - public/javascripts/asyncjs.jquery.js
    - public/javascripts/jquery.autosize.min.js
    - public/javascripts/vendor/placeholder-polyfill.min.js
    - public/javascripts/bootstrap-redu.js
    - public/javascripts/vendor/bootstrap-scrollspy.js
    - public/javascripts/swfobject.js # Necessário ao browserdetection.js
    - public/javascripts/browserdetection.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/outdated-browser.js
    - public/javascripts/landing.js
  common:
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/modernizr.js
    - public/javascripts/jquery.tipTip.minified.js
    - public/javascripts/folders.js
    - public/javascripts/exercises.js
    - public/javascripts/lectures.js
    - public/javascripts/swfobject.js
    - public/javascripts/jquery.iframe-transport.js
    - public/javascripts/jquery.remotipart.js
    - public/javascripts/lazyload.js
    - public/javascripts/jquery.fcbkcomplete.min.js
    - public/javascripts/jquery.tokeninput.js
    - public/javascripts/jquery.filestyle.mini.js
    - public/javascripts/jquery.placeholder.js
    - public/javascripts/form.redu.jquery.js
    - public/javascripts/asyncjs.jquery.js
    - public/javascripts/users.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/ytpreview.jquery.js
    - public/javascripts/subjects.js
    - public/javascripts/statuses.js
    - public/javascripts/admin.js
    - public/javascripts/partner.js
    - public/javascripts/jquery.nested-fields.js
    - public/javascripts/browserdetection.js
    - public/javascripts/outdated-browser.js
    - public/javascripts/jquery.noisy.js
    - public/javascripts/underscore.js
    - public/javascripts/underscore-sharing-template.redu.jquery.js
    - public/javascripts/embedly.redu.jquery.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/timeago.js
    - public/javascripts/bootstrap-redu-dropdown.js
  chat:
    - public/javascripts/jquery.pjax.js
    - public/javascripts/pusher.js
    - public/javascripts/jquery.json.js
    - public/javascripts/jquery.linkify-1.0.js
    - public/javascripts/chat.jquery.js
    - public/javascripts/chat.js
    - public/javascripts/loading.js
  chart:
    - public/javascripts/highcharts/highcharts.js
    - public/javascripts/d3/d3.js
    - public/javascripts/d3/d3.chart.js
    - public/javascripts/d3/d3.layout.js
    - public/javascripts/jquery.form.js
    - public/javascripts/teacher_participation.js
    - public/javascripts/subject_participation.js
    - public/javascripts/lectures_participation.js
    - public/javascripts/graph_form.js
    - public/javascripts/treemap.js
  ie:
    - public/javascripts/json2.js
    - public/javascripts/selectivizr.js
  user:
    - public/javascripts/jquery.maskedinput.js
  ckeditor:
    - public/javascripts/ckeditor/ckeditor.js
  clean:
    - public/javascripts/rails.js
    - public/javascripts/modernizr.js
    - public/javascripts/lazyload.js
    - public/javascripts/asyncjs.jquery.js
    - public/javascripts/jquery.noisy.js
    - public/javascripts/jquery.placeholder.js
    - public/javascripts/form.redu.jquery.js
    - public/javascripts/swfobject.js # Necessário ao browserdetection.js
    - public/javascripts/browserdetection.js
    - public/javascripts/jquery.cookie.js
    - public/javascripts/outdated-browser.js
    - public/javascripts/clean.js
  canvas:
    - public/javascripts/easyXDM.js
    - public/javascripts/canvas.js
  olark:
    - public/javascripts/olark.js

stylesheets:
  new_application:
    - public/stylesheets/icons.redu.css
    - public/stylesheets/utils.css
    - public/stylesheets/bootstrap-redu.css
    - public/stylesheets/home.css
    - public/stylesheets/wall.css
    - public/stylesheets/fb_style.css
    - public/stylesheets/outdated-browser-new.css
  landing:
    - public/stylesheets/bootstrap-redu.css
    - public/stylesheets/landing-new.css
    - public/stylesheets/outdated-browser-new.css
    - public/stylesheets/icons.redu.css
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/token-input.css
    - public/stylesheets/utils.css
    - public/stylesheets/wall.css
    - public/stylesheets/new-style.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/ajaxful_rating.css
    - public/stylesheets/fb_style.css
    - public/stylesheets/form.redu.css
    - public/stylesheets/table.redu.css
    - public/stylesheets/icons.big.redu.css
    - public/stylesheets/icons.redu.css
    - public/stylesheets/users.css
    - public/stylesheets/lectures.css
    - public/stylesheets/exercises.css
    - public/stylesheets/outdated-browser.css
    - public/stylesheets/chart.css
    - public/stylesheets/bootstrap-redu-nav-global.css
    - public/stylesheets/nav-global-icons.css
  ie:
    - public/stylesheets/ie.css
  ie8:
    - public/stylesheets/ie8.css
  chat:
    - public/stylesheets/chat.css
  clean:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/utils.css
    - public/stylesheets/icons.redu.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/form.redu.css
    - public/stylesheets/outdated-browser.css
    - public/stylesheets/clean.css
    - public/stylesheets/landing.css
    - public/stylesheets/fb-login.css
  cold:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/utils.css
    - public/stylesheets/tipTip.css
    - public/stylesheets/form.redu.css
    - public/stylesheets/icons.big.redu.css
    - public/stylesheets/icons.redu.css
    - public/stylesheets/outdated-browser.css
    - public/stylesheets/cold.css
    - public/stylesheets/errors.css
    - public/stylesheets/recover.css
  print:
    - public/stylesheets/reset.css
    - public/stylesheets/new-fonts.css
    - public/stylesheets/new-style.css
    - public/stylesheets/print.css
  page:
    - public/stylesheets/reset.css
    - public/stylesheets/new-fonts.css
